### ISSUE TITLE
Marius++ code/example request

### ISSUE THREAD

**Issue by 99snowleopards** [marius-team/marius#107]
**What is the documentation lacking? Please describe.**
A code example accompanying the Marius++ paper

**Describe the improvement you'd like**
A code example accompanying the Marius++ paper

**Additional context**
Thank you for releasing this amazing repo! Have you released the code/examples to accompany the Marius++ paper - it'd be great to be run Marius++ code to better understand the system. Thank you

**Comment by rogerwaleffe** [comment]
Thank you for reaching out! The code for the Marius++ paper (e.g., GNN training support) has actually already been merged into this repo! You can find examples which use GNNs for node classification here [Node Classification Config](http://marius-project.org/marius/examples/config/nc_ogbn_arxiv.html) and here [Node Classification Python](http://marius-project.org/marius/examples/python/nc_ogbn_arxiv.html). 

We plan to release a more detailed Marius++ artifact for reproducing the paper's experimental results in the future. In the mean time, let us know if you have any more immediate questions!

**Comment by 99snowleopards** [comment]
thank you so much for sharing the examples @rogerwaleffe - looking forward to the detailed Marius++ artifact

if I may ask one more question - the README says that the "Python API is currently experimental" and be used for certain features - it'd be very helpful if you could share a Roadmap for the development of the Python API - some details on features that have not been implemented yet and what order they might be implemented in would be super helpful,

thanks again!

**Comment by rogerwaleffe** [comment]
In terms of the Python API, right now it is indeed experimental. In general all the in-memory training features have been implemented and what is yet to be implemented is the out-of-core training features. For out-of-core training or for best performance the configuration interface should be used for now.

Thanks for the feedback! Maybe we can update the Python API documentation to include some information on the feature roadmap. 

Closing this issue.
