### ISSUE TITLE
[MariusGNN]Why does MariusGNN update embedding for link prediction?

### ISSUE THREAD

**Issue by Ningsir** [marius-team/marius#140]
For link prediction, MariusGNN will update embedding in [trainer.cpp](https://github.com/marius-team/marius/blob/eurosys_2023_artifact/src/cpp/src/trainer.cpp#L113-L119), but the baseline(dgl and pyg) does't update embedding.Why does MariusGNN update embedding for link prediction?

**Comment by JasonMoho** [comment]
Our implementations of DGL and PyG link prediction do update the node embedding parameters. See below.

DGL: 
- https://github.com/marius-team/marius/blob/eurosys_2023_artifact/experiment_manager/baselines/dgl/link_prediction.py#L433
- https://github.com/marius-team/marius/blob/eurosys_2023_artifact/experiment_manager/baselines/dgl/link_prediction.py#L209

PyG: 
- https://github.com/marius-team/marius/blob/eurosys_2023_artifact/experiment_manager/baselines/pyg/run_pyg.py#L294
- https://github.com/marius-team/marius/blob/eurosys_2023_artifact/experiment_manager/baselines/pyg/models.py#L52

**Comment by Ningsir** [comment]
thanks.
