### ISSUE TITLE
Remove dependency on Boost

### ISSUE THREAD

**Issue by JasonMoho** [marius-team/marius#17]
**Is your feature request related to a problem? Please describe.**
We currently use Boost for command line argument parsing and parsing .ini configuration files. 

Boost is very heavyweight and complicates the build process. Additionally, the download links to the boost library may fail: See #16. 

**Describe the solution you'd like**
We should remove the dependency on Boost by switching to a lightweight library which can parse .ini files and command line arguments with the same semantics.

The implementation with the new library should match functionality with the current implementation in Boost.

Modifications will be largely contained to `src/config.cpp`. 

One minor dependency on Boost's lockfree queues can be removed in `src/buffer.cpp` and replaced with traditional lock + queue data structure. 

**Describe alternatives you've considered**
We can implement our own parsing functionality if no libraries fit our requirements. 

**Additional context**
We might not be able to find a library which does both config parsing and the command line parsing. If we cannot, we should pick one which can do the config parsing and then implement our own command line parser.

**Comment by shivaram** [comment]
The other option is to include just the boost headers you use into our repo -- esp as I *think* boost headers are platform independent. This might be messy if we are using a large part of boost though

**Comment by shivaram** [comment]
https://github.com/jtilly/inih seems like a small INI parser that we could include for example. https://en.wikipedia.org/wiki/INI_file#Accessing_INI_files has some other candidates

**Comment by JasonMoho** [comment]
Yeah we can't use the boost headers since Boost::program_options doesn't have a header only option. Thanks for those links, we are looking into inih. Only issue is that it doesn't handle the command line args like Boost can.
