### ISSUE TITLE
error for final make step

### ISSUE THREAD

**Issue by realmarcin** [marius-team/marius#21]
**Describe the bug**

I am trying to build marius on a google cloud vm. The build went smoothly until the final step at which point I got an error at the linking step:

[100%] Built target marius
Scanning dependencies of target marius_train
[100%] Building CXX object CMakeFiles/marius_train.dir/src/marius.cpp.o
[100%] Linking CXX executable marius_train
/usr/bin/ld: libmarius.so: undefined reference to `std::filesystem::copy_file(std::filesystem::path const&, std::filesys
tem::path const&, std::filesystem::copy_options)'
/usr/bin/ld: libmarius.so: undefined reference to `std::filesystem::path::_M_split_cmpts()'
/usr/bin/ld: libmarius.so: undefined reference to `std::filesystem::status(std::filesystem::path const&)'
/usr/bin/ld: libmarius.so: undefined reference to `std::filesystem::rename(std::filesystem::path const&, std::filesystem
::path const&)'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/marius_train.dir/build.make:100: marius_train] Error 1
make[2]: *** [CMakeFiles/Makefile2:113: CMakeFiles/marius_train.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/marius_train.dir/rule] Error 2
make: *** [Makefile:188: marius_train] Error 2

**To Reproduce**

Follow the installation instruction from github README:

git clone https://github.com/marius-team/marius.git
cd marius
python3 -m pip install -r requirements.txt
mkdir build
cd build
cmake ../ -DUSE_CUDA=1
make marius_train -j

**Expected behavior**
The final step of the build should create marius executables, presumably in the build/bin directory.

**Environment**
This build was attempted on a google cloud vm with these parameters:

boot disk = tensorflow-2-4-20210414-140511-boot
Environment version = M65

I can provide more environment details after sshing into the instance, but not sure what is relevant for the above.

**Comment by JasonMoho** [comment]
Are you using GCC-9 and G++-9? I've seen those errors before when attempting to build with either gcc7 or gcc8.

**Comment by realmarcin** [comment]
Many thanks, the default system gcc was gcc7 and requiring the correct version got things working.

**Comment by JasonMoho** [comment]
Great! Closing this. Feel free to reopen/make a new issue if you hit anything else.
