### ISSUE TITLE
Configuration file modification script

### ISSUE THREAD

**Issue by AnzeXie** [marius-team/marius#48]
**Is your feature request related to a problem? Please describe.**
As mentioned in PR#45, we need a script which can perform conversion for example configuration files to new versions when changes to the configurations options are made.

**Describe the solution you'd like**
We need a script that can perform the following basic operations:
- remove section
- remove option
- add section
- add option

**Describe alternatives you've considered**
We can add additional functions in the future.

**Comment by JasonMoho** [comment]
Yeah this will be good for when we make changes to the configuration file schema. Will allow us to easily update the example configuration files when needed. Also it could be useful for users when they upgrade the system and need to migrate their existing configuration files to the new versions.
