### ISSUE TITLE
Add support for [source, destination] prediction in marius_predict

### ISSUE THREAD

**Issue by AnzeXie** [marius-team/marius#63]
**Is your feature request related to a problem? Please describe.**
Current version of ``marius_predict`` don't support prediction for datasets with only 1 relation type (no relation column).

**Describe the solution you'd like**
Enable ``marius_predict``  to perform link prediction for datasets with only 1 relation type.

**Comment by JasonMoho** [comment]
marius_predict does work with graphs without edge types.
