### ISSUE TITLE
Address strip error

### ISSUE THREAD

**Issue by AnzeXie** [marius-team/marius#70]
**Describe the bug**
Line 179 of ``csv_converter.py`` strips the ``output_dir`` address. In the case the address starts with ``/``, the leading ``/`` is also striped.

**To Reproduce**
1. When using ``preprocess.py``, enter the ``output_directory`` with an address starts with ``/``
2. See error

**Expected behavior**
The output_directory option should take any valid input addresses.

**Environment**
Any environment would have this problem.

**Comment by shivaram** [comment]
Can you edit the title of the issue - I think it should be "Address strip error"
