### ISSUE TITLE
Graph embeddings and graph classification 

### ISSUE THREAD

**Issue by bkrdmr** [marius-team/marius#98]
Hi, 
I've been reading the documentation for node classification and edge prediction tasks. I have a set of custom graphs I'd like to use for graph classification or graph-level embeddings for additional downstream tasks. Is this possible with the current version of Marius? 
Thank you.

**Comment by JasonMoho** [comment]
Unfortunately we don't currently support the graph classification task. That's something we have planned for the longer term.

Out of curiosity, how many graphs are in the dataset and what is their rough size (nodes/edges)? I don't have much familiarity with the graph classification workload beyond the [OGB datasets](https://ogb.stanford.edu/docs/graphprop/).
